name: Release CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
    - name: Universal Packaging
      run: |
        sbt universal:packageBin
        cd ~/work/lamoa/lamoa/target/universal/
        mv ./lamoa-*.zip ./lamoa.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
         files: ~/work/lamoa/lamoa/target/universal/lamoa.zip
         
