name: Release CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
    
on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
#     if: github.event.base_ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
    - name: Run packagin
      run: |
        sbt universal:packageBin
        cd ~/work/lamoa/lamoa/target/universal/
        mv ./lamoa-0.1.0-SNAPSHOT.zip ./lamoa.zip
#     - name: Packaging the artifact
#       uses: actions/upload-artifact@v2
#       with:
#             name: uinversal pack
#             path: ~/work/lamoa/lamoa/target/universal/lamoa.zip


    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ~/work/lamoa/lamoa/target/universal/lamoa.zip
