name: NativePackager

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run packagin
      run: |
        sbt universal:packageBin
        ls ~/work/lamoa/lamoa/target/scala-2.13/
        ls ~/work/lamoa/lamoa/target/scala-2.13/universal
        ls ~/work/lamoa/lamoa/target/universal/
#     - name: Packaging the artifact
#       uses: actions/upload-artifact@v2
#       with:
#             name: 
